// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASS_vyPTtFClvUM71JSdD3Lgvkb6JNgMI',
    appId: '1:824548619486:web:c0b817e258ad27ac337e4f',
    messagingSenderId: '824548619486',
    projectId: 'rc-mobil-control',
    authDomain: 'rc-mobil-control.firebaseapp.com',
    databaseURL: 'https://rc-coba-21c74-default-rtdb.firebaseio.com/',
    storageBucket: 'rc-mobil-control.appspot.com',
    measurementId: 'G-EV43RKZDNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtLqSQmY9PfpzyMN_NCiCmH6VUI14nbEY',
    appId: '1:824548619486:android:a96d9fc425142605337e4f',
    messagingSenderId: '824548619486',
    projectId: 'rc-mobil-control',
    databaseURL: 'https://rc-coba-21c74-default-rtdb.firebaseio.com/',
    storageBucket: 'rc-mobil-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADjG_cZySdkZ066Lt6IcfRx73GMAbAp7Q',
    appId: '1:824548619486:ios:038c78a092dea1e5337e4f',
    messagingSenderId: '824548619486',
    projectId: 'rc-mobil-control',
    databaseURL: 'https://rc-coba-21c74-default-rtdb.firebaseio.com/',
    storageBucket: 'rc-mobil-control.appspot.com',
    iosBundleId: 'com.example.p',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADjG_cZySdkZ066Lt6IcfRx73GMAbAp7Q',
    appId: '1:824548619486:ios:f6257dbba50e14b5337e4f',
    messagingSenderId: '824548619486',
    projectId: 'rc-mobil-control',
    databaseURL: 'https://rc-coba-21c74-default-rtdb.firebaseio.com/',
    storageBucket: 'rc-mobil-control.appspot.com',
    iosBundleId: 'com.example.p.RunnerTests',
  );
}
